services:
  - type: web
    name: telegram-ai-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port $PORT --log-level warning
